set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(DEBARCH armel)
set(ZENOHC_CUSTOM_TARGET arm-unknown-linux-gnueabi)
set(ZENOHC_CARGO_FLAGS "--config=target.arm-unknown-linux-gnueabi.linker=\"arm-linux-gnueabi-gcc\"")
set(CMAKE_C_COMPILER arm-linux-gnueabi-gcc)
set(CMAKE_CXX_COMPILER arm-linux-gnueabi-g++)