set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7)
set(DEBARCH armhf)
set(ZENOHC_CUSTOM_TARGET armv7-unknown-linux-gnueabihf)
set(ZENOHC_CARGO_FLAGS "--config=target.armv7-unknown-linux-gnueabihf.linker=\"armv7-linux-gnueabihf-gcc\"")
set(CMAKE_C_COMPILER armv7-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER armv7-linux-gnueabihf-g++)