[package]
name = "prebindgen-project-root"
version = "0.4.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Utility to expose the workspace project root at build time"
publish = false

[build-dependencies]
project-root = "0.2"
quote = "1"
