name: Check required labels

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
    branches: ["**"]

jobs:
  check-labels:
    name: Check PR labels
    uses: eclipse-zenoh/ci/.github/workflows/check-labels.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      pull-requests: write
